global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pairly-backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/metrics'

  - job_name: 'pairly-executor'
    static_configs:
      - targets: ['executor:2112']
    metrics_path: '/metrics'